graphite:
  image: mosquito/graphite:latest
  ports:
    - "81:80"
    - "2003:2003"
    - "2003:2003/udp"
  volumes:
    - "/tmp/graphite:/opt/graphite/storage"
    - "/tmp/graphite:/var/log/supervisor"

grafana:
  image: mosquito/grafana:latest
  ports:
    - "80:80"
  volumes:
    - "/tmp/grafana:/var/lib/grafana"
  environment:
    ADMIN_USER: "admin"
    ADMIN_PASSWORD: "admin"
    ALLOW_SIGNUP: "false"
